services:
  backend-golang:
    build:
      context: ./backend/golang
      target: dev
    ports:
      - "8080:8080"
    container_name: go-backend
    user: 1000:1000
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    volumes:
      - ./backend/golang:/app
  backend-django:
    build:
      context: ./backend/django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: django-backend
    user: 1000:1000
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    volumes:
      - ./backend/django:/app
    command: sh -c "./manage.py migrate && ./manage.py account_init_develop && ./manage.py runserver 0.0.0.0:8000"
    

  frontend:
    build:
      context: frontend/ui
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    container_name: next-frontend
    user: 1000:1000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ${HOME}/.vscode-server-portfolio:/home/node/.vscode-server
    command: sh -c "npm install && npm run dev"


  postgres:
    image: postgres:15
    container_name: postgres_portfolio
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
