root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp"]
  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  time = true

[misc]
  clean_on_exit = true
